kind: pipeline
name: build
type: kubernetes

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    repo: rkojedzinszky/kea
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true

  privileged: true
  volumes:
    - name: docker
      path: /var/lib/docker

volumes:
  - name: docker
    temp: {}
