kind: pipeline
name: build

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    repo: registry.lan/krichy/kea
    registry: registry.lan
    insecure: true
    auto_tag: true
